# Angular
# Build and test Angular Projects.
# Autor: Zama Bandeira Braga <zamabraga@wiz.co>
# Mais informação: https://wizco.topdesk.net/tas/public/ssp/content/detail/knowledgeitem?unid=e7d0f51ade324ec289891b0892dd0837
# Issues: https://wizco.topdesk.net/tas/public/ssp/content/serviceflow?unid=3cd6a6f61e4a49689212298c0cdbd427&from=86304f95-4cc7-46aa-ae25-1c6af55eafc5&openedFromService=true
# Exemplos: https://dev.azure.com/wizsolucoes/WizPipelines/_git/exemplos

resources:
  repositories:
    - repository: coretemplate
      type: git
      name: WizPipelines/core-template
      ref:  refs/heads/v2

pool:
  vmImage: ubuntu-latest

trigger:
  batch: 'true'
  branches:
    exclude: [ 'refs/heads/feature/*' ]
  paths:
    exclude:
      - README.md
      
extends:
  template: angular/modulo.yml@coretemplate
  parameters:
    produtoDigital: <%= PRODUCT_NAME%>
    nodeVersion: "18.x"
    modulos: 
      - <%= folderName%>