name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build-publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          scope: '@wizco'
          always-auth: true
      - run: |
          cd application-webcomponents
          npm install
      - run: |
          cd application-webcomponents
          npm run build
      - run: |
          cd application-webcomponents
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
